<div id="content">

	<div id="searchForm">
		<form action="cauta" method="get">
			<div id="searchInput">
				<?php 
					if ($this->searchQuery!=""){
						$searchQuery = $this->searchQuery; 
					}else {
						$searchQuery = $this->translate("Search here");
					}
				?>
			    <input type="text" name="q" class="search" value="<?php echo $searchQuery;?>" title="<?php echo $searchQuery;?>" />
			</div>
			<input type="submit" id="searchSubmit" value="<?php echo $this->translate("Search")?>"/>
		</form>
	
	</div>

</div>
<?php  
if ($this->searchQuery==""){
	$this->headScript()->prependFile($this->baseUrl('/js/cautare.js'));
}
?>