<?php if (count($this->paginator)): ?>

<div id="informationBar">
	<div id="results"> 
	<?php echo $this->translate('Results'); ?>
	
	<?php echo ($this->pageNumber-1)*$this->perPage+1; ?>
	-
	<?php echo ($this->pageNumber)*$this->perPage; ?>	
	<?php echo $this->translate('from about'); ?>
	<?php echo $this->paginator->getTotalItemCount(); ?>
	</div>
</div>  
<ul id="search-results">
    <?php foreach ($this->paginator as $obiect): ?>
        <li>
            <h3>
               <a href="<?php echo $this->objectUrl($obiect) ?>"><?php echo $this->cautareHighlight($this->searchWords,$obiect->ObiectNume->nume); ?></a>
            </h3>
			<div class="relavance" style="width:<?php echo $this->listaRelevante[$obiect->nume];?>px"> </div>
            <div class="description">
                <?php echo $this->cautareHighlight($this->searchWords, $this->truncateString($obiect->ObiectNume->descriere,180)) ?>
            </div>
			
			
			<?php if (count($obiect->TagObiect)):?>
			 <ul class="labels">
				 <li class="first"><?php echo $this->translate('Posted in ');?></li>
			<?php endif?>
			
			<?php foreach ($obiect->TagObiect as $tag): ?>
				<li><a href="<?php echo $this->baseUrl('/cauta?q='.$tag->Tag->nume)?>"><?php echo $this->cautareHighlight($this->searchWords,$tag->Tag->nume);?></a></li>
			<?php endforeach; ?>
			
			<?php if (count($obiect->TagObiect)):?>
				 </ul>
			<?php endif ?>			
			<div class="city">
				<?php echo $this->translate('Found in ');?>
				<a href="<?php echo $this->baseUrl('/cauta?q='.ucwords($obiect->Localitate->name))?>">	
					<?php echo $this->cautareHighlight($this->searchWords,ucwords($obiect->Localitate->name));?>
				</a>
			</div>
			
        </li>
    <?php endforeach; ?>
</ul>

<?php
    if ($this->paginator instanceof Zend_Paginator and $this->paginator->getTotalItemCount()>$this->perPage) {
    	echo $this->paginator;
    }
?>

<?php else: ?>
    <div class="noresults">
        <?php echo $this->translate("Sorry, nothing found. Please insert coin and try again.") ?><br/>
        
        <a href="<?php echo $this->baseUrl('/intrebare/adauga') ?>"><?php echo $this->translate("Ask the community where you could find this thing.") ?></a>
    </div>
<?php endif; ?>