<?php 
  $this->headLink()
	    ->prependStylesheet($this->baseUrl('css/cautare.css'));
		
?>
<?php 
	echo $this->render('cauta/box_cauta.phtml');
?>
		
		
<h3><?php echo $this->searchQuery;?></h3>
<hr/>
<ul id="search-results">
    <?php foreach ($this->paginator as $obiect): ?>
        <li>
            <h3>
               <a href="<?php echo $this->objectUrl($obiect) ?>"><?php echo $this->cautareHighlight($this->searchWords,$obiect->ObiectNume->nume); ?></a>
            </h3>
			<div class="relavance" style="width:<?php echo $this->listaRelevante[$obiect->nume];?>px"> </div>
            <div class="description">
                <?php echo $this->cautareHighlight($this->searchWords, $this->truncateString($obiect->ObiectNume->descriere,180)) ?>
            </div>
			
			
			<?php if (count($obiect->TagObiect)):?>
			 <ul class="labels">
				 <li class="first"><?php echo $this->translate('Posted in ');?></li>
			<?php endif?>
			
			<?php foreach ($obiect->TagObiect as $tag): ?>
				<li><a href="<?php echo $this->baseUrl('/cauta?q='.$tag->Tag->nume)?>"><?php echo $this->cautareHighlight($this->searchWords,$tag->Tag->nume);?></a></li>
			<?php endforeach; ?>
			
			<?php if (count($obiect->TagObiect)):?>
				 </ul>
			<?php endif ?>			
			
			
			
        </li>
    <?php endforeach; ?>
</ul>

<?php
    if ($this->paginator instanceof Zend_Paginator) {
    	echo $this->paginator;
    }
?>

