<?php

/**
 * Intrebare
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Intrebare extends BaseIntrebare
{
    public static function addNew($values)
    {
        $intrebare = new Intrebare;
        $intrebare->question = $values['question'];
        $intrebare->user     = Zend_Auth::getInstance()->getIdentity();
        $intrebare->added    = time();

        if (!empty($values['location'])) {
            $localitate = Doctrine_Core::getTable('Localitate')->findOneByName(strtolower($values['location']));

            if ($localitate) {
                $intrebare->localitate = $localitate;
            } else {
                $localitate = new Localitate;
                $localitate->name = strtolower($values['location']);
                $localitate->save();
                
                $intrebare->localitate = $localitate;
            }
        }
        
        $intrebare->save();
    }
}