<?php

/**
 * Obiect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Obiect extends BaseObiect
{
    public function setUp()
    {
        $this->hasOne('ObiectNume', array(
             'local' => 'nume',
             'foreign' => 'id'));
             
         $this->hasMany('TagObiect', array(
               'local' => 'id',
               'foreign' => 'obiect'));
             
        parent::setUp();
    }
}