<?php

/**
 * Tag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Tag extends BaseTag
{
    public function setUp()
    {
        $this->hasMany('TagObiect', array(
              'local' => 'id',
              'foreign' => 'tag'));
        
        parent::setUp();
    }
}