<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
    /**
     * Log in
     *
     * @param string $email 
     * @param string $password 
     * @return void
     * @author Valentin Bora
     */
    public static function logIn($email, $password) {
        $auth = Zend_Auth::getInstance();
        $authAdapter = new Gasestema_Auth_Database(
            $email,
            sha1($password)
        );

        $result = $auth->authenticate($authAdapter);
        
        if (!$result->isValid()) {
            throw new Exception('The email and/or password you entered are incorrect.');
        }
        
        return true;
    }
}