<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?php echo $this->headTitle('Gaseste-ma')->setSeparator(" - ") ?>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<?php echo $this->headMeta() ?>
	
    <?php echo $this->headLink()
	    ->prependStylesheet($this->baseUrl('/css/main.css'))
?>
</head>
<body class="home">
    <div id="wrap">
        <div id="user">
            <?php echo $this->render('/user/miniprofile.phtml') ?>
        </div>
        
        <div class="main">
            <h1 class="logo"><a href="<?php echo $this->baseUrl() ?>" title="<?php echo $this->translate("Go to the home page") ?>"></a></h1>
    	    <?php echo $this->render("/cauta/box_cauta.phtml") ?>
    	</div>
    	
    	<?php echo $this->render("footer.phtml") ?>
    </div>
	
<?php echo $this->headScript()
	    ->prependFile($this->baseUrl('/js/main.js'))
	    ->prependFile($this->baseUrl('/js/jquery-1.4.2.min.js'))
?>
<script type="text/javascript">
	searchErrorMessage = "<?php echo $this->translate("Scrie ceva!")?>";
</script>
</body>
</html>