<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?php echo $this->headTitle('Gaseste-ma')->setSeparator(" - ") ?>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<?php echo $this->headMeta() ?>
	
    <?php echo $this->headLink()
	    ->prependStylesheet($this->baseUrl('/css/main.css'))
?>
</head>
<body>
    <div id="wrap">
        <div class="header">
            <div id="user">
                <?php if (!$this->user): ?>
                    <a href="<?php echo $this->baseUrl('/user/login') ?>">Log in</a>
                <?php else: ?>
                    <?php echo $this->translate("Hello, %1\$s", $this->user->realname) ?><br/>
                    <a href="<?php echo $this->baseUrl('/user/logout') ?>">Log out</a>
                <?php endif; ?>
            </div>
        </div>
        
    	<?php echo $this->layout()->content; ?>
    </div>
	
<?php echo $this->headScript()
	    ->prependFile($this->baseUrl('/js/main.js'))
	    ->prependFile($this->baseUrl('/js/jquery-1.4.2.min.js'))
?>
</body>
</html>