<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title><?php echo $this->headTitle() ?></title>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<?php echo $this->headMeta() ?>
	
    <?php echo $this->headLink()
	    ->prependStylesheet($this->baseUrl('/css/main.css'))
?>
</head>
<body>
	<?php echo $this->layout()->content; ?>
	
<?php echo $this->headScript()
	    ->prependFile($this->baseUrl('/js/main.js'))
	    ->prependFile($this->baseUrl('/js/jquery-1.4.2.min.js'))
?>
</body>
</html>