<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?php echo $this->headTitle('Gaseste-ma')->setSeparator(" - ") ?>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
	<?php echo $this->headMeta() ?>
	
    <?php echo $this->headLink()
	    ->prependStylesheet($this->baseUrl('/css/main.css'))
	    ->prependStylesheet($this->baseUrl('css/cautare.css'));
		
?>
</head>
<body>
    <div id="wrap">
        <div class="header">
            <h1 class="logo"><a href="<?php echo $this->baseUrl() ?>" title="<?php echo $this->translate("Go to the home page") ?>"></a></h1>
            <div id="user">
                <?php echo $this->render('/user/miniprofile.phtml') ?>
            </div>
        </div>
        
        <div class="main">
            <?php 
            	echo $this->render('cauta/box_cauta.phtml');
            ?>
            
            <div class="content">
    	        <?php echo $this->layout()->content; ?>
    	    </div>
    	</div>
    	
    	<?php echo $this->render("footer.phtml") ?>
    </div>
	
<?php echo $this->headScript()
	    ->prependFile($this->baseUrl('/js/main.js'))
	    ->prependFile($this->baseUrl('/js/jquery-1.4.2.min.js'))
	    ->prependFile($this->baseUrl('/js/cufon/Omnes_500.font.js'))
        ->prependFile($this->baseUrl('/js/cufon/cufon.js'))
        ->prependScript('var baseUrl = "' . $this->baseUrl() . '"')
?>
<script type="text/javascript">
	searchErrorMessage = "<?php echo $this->translate("Scrie ceva!")?>";
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-15180782-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
  })();

</script>

</body>
</html>