<form action="<?php echo $this->baseUrl('/locatie/adauga') ?>" method="post" class="locatie">
    <fieldset>
        <legend><?php echo $this->translate("Add location") ?></legend>
        <table>
            <tbody>
                <?php echo $this->form->getElement('name')->render() ?> <br/>
                
                <tr>
                    <td colspan="2">
                        <h3><?php echo $this->translate("Localization") ?></h3>            
                    </td>
                </tr>
                
                <?php echo $this->form->getElement('location')->render() ?>
                
                <?php echo $this->form->getElement('address')->render() ?>
                
                <?php echo $this->form->getElement('link')->render() ?>
                
                <tr>
                    <td></td>
                    <td>
                        <a href="#" class="map-trigger"><?php echo $this->translate('Point on the map?') ?></a><br/>
                        <div id="map"></div>
                    </td>
                </tr>
                
                <tr>
                    <td colspan="2" class="underline">
                        <?php if (isset($this->locationError)): ?>
                            <span class="insistent"><?php echo $this->translate("We insist! Please add some form of location information.") ?></span>
                        <?php endif; ?>
                        
                        <?php echo $this->translate("You have to add at least one type of location: address, link or point on the map.") ?>
                    </td>
                </tr>
                
                <tr>
                    <td colspan="2'">
                        <h3><?php echo $this->translate("Optional information") ?></h3>
                    </td>
                </tr>
                
                <?php echo $this->form->getElement('contact')->render() ?>
                <?php echo $this->form->getElement('description')->render() ?>
                <?php echo $this->form->getElement('schedule')->render() ?>
                
                <tr>
                    <td><?php echo $this->translate("Logo:") ?> </td>
                    <td><input type="file" id="logo" name="logo" /></td>
                </tr>
                
                <tr>
                    <td><?php echo $this->form->getElement('submit')->render() ?></td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <?php echo $this->form->getElement('lat')->render() ?>
        <?php echo $this->form->getElement('long')->render() ?>
    </fieldset>
</form>

<?php $this->headScript()
->appendScript('var lat=' . $this->user->Localitate->lat . '; var long = ' . $this->user->Localitate->long . ';')
    ->appendFile('http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=true_or_false&amp;key=ABQIAAAA-lYx-T3mkl9LSdThSrGqgRS3ftUSf5MieQdEflS8ZKtpZjkCEBTlIq9Z1XO7uW3FIOHHfDxmk1en1g"')
    ->appendFile($this->baseUrl('js/locatie/add.js'));

    $this->headLink()->appendStylesheet($this->baseUrl('/css/locatie.css'));
?>