<h2><?php echo $this->locatie->nume ?></h2>

<div id="location-data">
    <div class="description">
        <?php echo $this->locatie->descriere ?>
    </div>
    
    <div class="schedule">
        <?php echo $this->translate("Schedule:") ?> <?php echo $this->locatie->orar ?>
    </div>
    
    <div class="contact">
        <?php echo $this->translate("Contact:") ?> <?php echo $this->locatie->contact ?>
    </div>
</div>

<h2><?php echo $this->translate("Objects available in this location:") ?></h2>
<ul id="location-producs">
    <?php foreach ($this->obiecte as $obiect): ?>
        <li>
            <span class="name">
                <a href="<?php echo $this->objectUrl($obiect) ?>"><?php echo $obiect->ObiectNume->nume ?></a>
            </span><br/>
            <span class="description">
                >> <?php echo $obiect->descriere ?>
            </span>
        </li>
    <?php endforeach; ?>
</ul>